Add readme and dependencies
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #1
Opened 2021-12-09 13:09 UTC by Morel-Victor

2021-12-09 13:15 UTC, Caroline-CD requested changes

2021-12-09 13:15 UTC, Caroline-CD commented on README.md
> +3 - run your local server `npm run start`
It's more like "npm start" no ?

2021-12-09 13:18 UTC, Caroline-CD approved these changes

2021-12-15 08:22 UTC, Hacene010 approved these changes

2021-12-15 10:11 UTC, merged