Header
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #2
Opened 2021-12-15 12:57 UTC by Morel-Victor

Create Header and Searchbar in header

2021-12-15 13:54 UTC, Caroline-CD approved these changes, later dismissed
Ok for me :+1:

2021-12-16 14:49 UTC, Hacene010 requested changes
Still some changes to make. See the comments

2021-12-16 14:49 UTC, Hacene010 commented on src/Components/Header/index.jsx
> +            {' '}
Plz remove this :)

2021-12-16 14:49 UTC, Hacene010 commented on src/Components/Header/index.jsx
> +        {open ? (
you can do it like this : {open && (...)}

2021-12-16 14:49 UTC, Hacene010 commented on src/Components/Header/style.jsx
> +export default {
How can this work ??? Did you run 'npm run prepare' to prepare husky ?

2021-12-16 14:49 UTC, Hacene010 commented on src/Components/SearchBar/style.jsx
> +  display: flex;
Normally with 'display: flex' your items are online. So I don't see the use of 'flex-direction: row'

2021-12-16 15:49 UTC, Caroline-CD approved these changes
Ok for me :100:

2021-12-16 17:09 UTC, Hacene010 approved these changes

2021-12-16 19:04 UTC, merged