Cars
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #20
Opened 2022-01-13 16:24 UTC by John-athan14

2022-01-13 16:30 UTC, Caroline-CD requested changes
Please can you remove comments :)

2022-01-13 16:30 UTC, Caroline-CD commented on src/Components/VéhiculeCard/index.jsx
> +  // const handleClick = () => {
Please remove all comments.

2022-01-13 16:30 UTC, Caroline-CD commented on src/Components/VéhiculeCard/index.jsx
> +// import useState from 'react';
Please remove comments

2022-01-13 16:30 UTC, Caroline-CD commented on src/Pages/Cars/index.jsx
> +      console.log(data);
Please, remove console.log

2022-01-13 16:30 UTC, Caroline-CD commented on src/Pages/CarsDetails/index.jsx
> +// import Clio2 from '../../Assets/clio2.png';
Please remove comments

2022-01-13 16:30 UTC, Caroline-CD commented on src/Pages/CarsDetails/index.jsx
> +          {/* <div className='Picture2'>
Please remove comments

2022-01-13 16:30 UTC, Caroline-CD commented on src/Pages/CarsDetails/index.jsx
> +        {/* <div>
Please remove comments

2022-01-13 16:30 UTC, Caroline-CD commented on src/Pages/CarsDetails/style.jsx
> +  flex-direction: column;
please, remove comments

2022-01-13 16:35 UTC, John-athan14 commented on src/Components/VéhiculeCard/index.jsx
> +  // const handleClick = () => {
comments remove

2022-01-14 10:09 UTC, John-athan14 commented
Remove comments code

2022-01-14 10:17 UTC, Caroline-CD approved these changes
Ok for me

2022-01-17 09:56 UTC, Franck59840 approved these changes

2022-01-17 09:57 UTC, merged