Vote card
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #21
Opened 2022-01-13 16:31 UTC by NacymeG

2022-01-13 16:35 UTC, Caroline-CD approved these changes
OK :+1:

2022-01-14 10:53 UTC, Hacene010 requested changes
Some evils to correct

2022-01-14 10:53 UTC, Hacene010 commented on src/Components/VoteCard/index.jsx
> +// import LinearProgress from '@mui/material/LinearProgress';
dead code !!!

2022-01-14 10:53 UTC, Hacene010 commented on src/Components/VoteCard/style.jsx
> +  progress::-webkit-progress-bar {
if you add a blank line before, why don't you add it here?

2022-01-14 10:53 UTC, Hacene010 commented on src/Components/VoteCard/index.jsx
> +        <button type="button" onClick={upvote}>
camelCase into the onClick

2022-01-14 10:53 UTC, Hacene010 commented on src/Pages/VotePage/index.jsx
> +          Votez pour le véhicule que vous souhaitez rétrofité. Une fois le
a small content change "...que vous souhaitez rétrofiter.."

2022-01-14 10:53 UTC, Hacene010 commented on src/Pages/VotePage/style.jsx
> +
empty line

2022-01-14 10:53 UTC, Hacene010 commented on src/Pages/VotePage/style.jsx
> +
empty line

2022-01-14 10:53 UTC, Hacene010 commented on src/Pages/VotePage/style.jsx
> +    flex-direction: row;
You can use flex-flow: row wrap; here.

2022-01-14 13:11 UTC, Caroline-CD approved these changes, later dismissed
Ok :+1: for me

2022-01-17 09:42 UTC, Morel-Victor approved these changes, later dismissed
Ok for me !

2022-01-17 13:11 UTC, Hacene010 submitted a review, later dismissed

2022-01-17 13:17 UTC, Morel-Victor submitted a review, later dismissed

2022-01-17 13:19 UTC, Morel-Victor approved these changes

2022-01-17 13:26 UTC, Hacene010 approved these changes

2022-01-17 13:31 UTC, merged