Vote page
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #26
Opened 2022-01-17 13:39 UTC by NacymeG

2022-01-17 14:15 UTC, Morel-Victor approved these changes, later dismissed

2022-01-17 15:52 UTC, Hacene010 requested changes
small evils

2022-01-17 15:52 UTC, Hacene010 commented on src/Components/VoteCard/index.jsx
> +          // console.log(error);
dead code

2022-01-17 15:52 UTC, Hacene010 commented on src/Components/VoteCard/index.jsx
> +        <p className="PriceArea">A partir de {car.price}€</p>
camelCase for classNames

2022-01-18 09:10 UTC, Morel-Victor approved these changes, later dismissed

2022-01-18 12:21 UTC, Morel-Victor approved these changes

2022-01-18 14:48 UTC, Hacene010 approved these changes

2022-01-18 14:58 UTC, merged