Homepage
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #3
Opened 2021-12-15 16:00 UTC by NacymeG

2021-12-15 16:25 UTC, Caroline-CD commented on src/Pages/Home/index.jsx
> +                classique est trop élevé ? Nous avons la solution !
The client's spelling mistakes will have to be corrected

2021-12-15 16:27 UTC, Caroline-CD approved these changes
Ok for me

2021-12-16 15:39 UTC, Hacene010 requested changes
Some evils. See the comments

2021-12-16 15:39 UTC, Hacene010 commented on src/App.jsx
> +      <Home />
I think you forgot to remove this component

2021-12-16 15:39 UTC, Hacene010 commented on src/Components/Header/style.jsx
> +export const SHeader = styled.div`
You must remove all these exports and put your const into the last export without the default word

2021-12-16 15:39 UTC, Hacene010 commented on src/Components/SearchBar/style.jsx
> +export const Ssearchbar = styled.div`
Same here for the exports

2021-12-16 15:39 UTC, Hacene010 commented on src/Pages/Home/index.jsx
> +          <br /> <br />
all these br  are ugly :/

2021-12-16 15:39 UTC, Hacene010 commented on src/Pages/Home/index.jsx
> +          <NewsCardContainer>
a .map here is more appropriate, isn't it?

2021-12-16 16:16 UTC, closed without merging