Change design and responsive for form footer
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #30
Opened 2022-01-18 16:13 UTC by Morel-Victor

2022-01-19 08:40 UTC, Caroline-CD submitted a review, later dismissed
ok for me :+1:

2022-01-19 15:37 UTC, Hacene010 requested changes

2022-01-19 15:37 UTC, Hacene010 commented on src/Components/Form/index.jsx
> +        <p>Envoyer</p>
Why did you add a p tag here ?

2022-01-24 10:05 UTC, Morel-Victor commented on src/Components/Form/index.jsx
> +        <p>Envoyer</p>
Done !

2022-01-24 13:26 UTC, Caroline-CD approved these changes, later dismissed
Okk for me

2022-01-24 13:45 UTC, Caroline-CD approved these changes
ok for me :)

2022-01-24 16:38 UTC, Hacene010 approved these changes

2022-01-25 08:16 UTC, merged