Setting up the footer and styling in desktop mode
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #4
Opened 2021-12-16 15:56 UTC by Caroline-CD

2021-12-16 16:06 UTC, Morel-Victor submitted a review, later dismissed
All is good for me !

2021-12-16 17:08 UTC, Hacene010 requested changes
Some evils to correct

2021-12-16 17:08 UTC, Hacene010 commented on src/components/Footer/Style.jsx
> +export const SFooter = styled.footer`
reconsider your exports (Ask Victor)

2021-12-16 22:34 UTC, Morel-Victor approved these changes
Ok for me :)

2021-12-17 08:15 UTC, Hacene010 approved these changes

2021-12-17 11:21 UTC, merged