Overall fixes
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #41
Opened 2022-01-31 11:03 UTC by NacymeG

2022-01-31 13:58 UTC, Caroline-CD submitted a review, later dismissed

2022-01-31 16:11 UTC, Hacene010 requested changes

2022-01-31 16:11 UTC, Hacene010 commented on src/Pages/CarsDetails/index.jsx
> +                OUI <input type="checkbox" name="toto" />
good try ;-)
But no toto on github !

2022-01-31 16:53 UTC, Hacene010 submitted a review, later dismissed

2022-02-01 08:29 UTC, Caroline-CD submitted a review, later dismissed
ok :100:

2022-02-01 12:51 UTC, Hacene010 submitted a review, later dismissed

2022-02-01 15:22 UTC, Caroline-CD approved these changes

2022-02-01 15:31 UTC, Hacene010 approved these changes

2022-02-01 15:35 UTC, merged