News card&scrollbar
WildCodeSchool/p3-g3-sept21-lille-reactJs-retrofit-frontend pull request #9
Opened 2021-12-22 11:18 UTC by NacymeG

2021-12-22 11:24 UTC, Caroline-CD approved these changes, later dismissed
Good for me :100:

2021-12-22 14:57 UTC, Hacene010 requested changes
some evils

2021-12-22 14:57 UTC, Hacene010 commented on src/Components/NewsCard/style.jsx
> +
empty line to remove here !

2021-12-22 14:57 UTC, Hacene010 commented on src/Components/NewsCard/style.jsx
> +
same here

2021-12-22 14:57 UTC, Hacene010 commented on src/Components/NewsCard/style.jsx
> +
here too

2021-12-22 14:57 UTC, Hacene010 commented on src/Components/NewsCard/style.jsx
> +
: /

2021-12-22 14:57 UTC, Hacene010 commented on src/Components/NewsCard/style.jsx
> +
-_-

2022-01-03 08:57 UTC, Caroline-CD approved these changes
OK :100: it's ok for me

2022-01-03 09:33 UTC, Hacene010 approved these changes

2022-01-03 09:43 UTC, merged